package com.company;

public class Convertor {
    String convert(int inputNumber) {
        switch (inputNumber) {
            case 1:
                return "I";
            case 2:
                return "Ii";
            case 3:
                return "Iii";
            case 4:
                return "Iv";
            case 5:
                return "v";
            case 6:
                return "vI";
            case 7:
                return "viI";
            case 8:
                return "vIii";
            case 9:
                return "Ix";
            case 10:
                return "x";
            case 11:
                return "xi";
            case 12:
                return "xii";
            case 13:
                return "xiii";
            case 14:
                return "xiv";
            case 15:
                return "xv";
            case 16:
                return "xvi";
            case 17:
                return "xvii";
            case 18:
                return "xviii";
            case 19:
                return "xix";
            case 20:
                return "xx";
            case 21:
                return "xxi";
            case 22:
                return "xxii";
            case 23:
                return "xxiii";
            case 24:
                return "xxiv";
            case 25:
                return "xxv";
            case 26:
                return "xxvi";
            case 27:
                return "xxvii";
            case 28:
                return "xxviii";
            case 29:
                return "xxix";
            case 30:
                return "xxx";
            case 31:
                return "xxxi";
            case 32:
                return "xxxii";
            case 33:
                return "xxxiii";
            case 34:
                return "xxxiv";
            case 35:
                return "xxxv";
            case 36:
                return "xxxvi";
            case 37:
                return "xxxvii";
            case 38:
                return "xxxviii";
            case 39:
                return "xxxix";
            case 40:
                return "xl";
            case 41:
                return "xli";
            case 42:
                return "xlii";
            case 43:
                return "xliii";
            case 44:
                return "xliv";
            case 45:
                return "xlv";
            case 46:
                return "xlvi";
            case 47:
                return "xlvii";
            case 48:
                return "xlviii";
            case 49:
                return "xlix";
            case 50:
                return "l";
            case 51:
                return "li";
            case 52:
                return "lii";
            case 53:
                return "liii";
            case 54:
                return "liv";
            case 55:
                return "lv";
            case 56:
                return "lvi";
            case 57:
                return "lvii";
            case 58:
                return "lviii";
            case 59:
                return "lix";
            case 60:
                return "lx";
            case 61:
                return "lxi";
            case 62:
                return "lxii";
            case 63:
                return "lxiii";
            case 64:
                return "lxiv";
            case 65:
                return "lxv";
            case 66:
                return "lxvi";
            case 67:
                return "lxvii";
            case 68:
                return "lxviii";
            case 69:
                return "lxix";
            case 70:
                return "lxx";
            case 71:
                return "lxxi";
            case 72:
                return "lxxii";
            case 73:
                return "lxxiii";
            case 74:
                return "lxxiv";
            case 75:
                return "lxxv";
            case 76:
                return "lxxvi";
            case 77:
                return "lxxvii";
            case 78:
                return "lxxviii";
            case 79:
                return "lxxix";
            case 80:
                return "lxxx";
            case 81:
                return "lxxxi";
            case 82:
                return "lxxxii";
            case 83:
                return "lxxxiii";
            case 84:
                return "lxxxiv";
            case 85:
                return "lxxxv";
            case 86:
                return "lxxxvi";
            case 87:
                return "lxxxvii";
            case 88:
                return "lxxxviii";
            case 89:
                return "lxxxix";
            case 90:
                return "xc";
            case 91:
                return "xci";
            case 92:
                return "xcii";
            case 93:
                return "xciii";
            case 94:
                return "xciv";
            case 95:
                return "xcv";
            case 96:
                return "xcvi";
            case 97:
                return "xcvii";
            case 98:
                return "xcviii";
            case 99:
                return "xcix";
        }
        return "c";
    }
}
